[2022-01-05 18:23:44,873] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: example_bash_operator.also_run_this scheduled__2022-01-04T00:00:00+00:00 [queued]>
[2022-01-05 18:23:44,880] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: example_bash_operator.also_run_this scheduled__2022-01-04T00:00:00+00:00 [queued]>
[2022-01-05 18:23:44,880] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-05 18:23:44,880] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-05 18:23:44,881] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-05 18:23:44,890] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): also_run_this> on 2022-01-04 00:00:00+00:00
[2022-01-05 18:23:44,894] {standard_task_runner.py:52} INFO - Started process 24855 to run task
[2022-01-05 18:23:44,901] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'example_bash_operator', 'also_run_this', 'scheduled__2022-01-04T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', '/Users/admin/opt/miniconda3/envs/airflow-tutorial/lib/python3.7/site-packages/airflow/example_dags/example_bash_operator.py', '--cfg-path', '/var/folders/3z/fyvld5jd6lxbb7nt49h4jx1h0000gn/T/tmpqrp2o6gu', '--error-file', '/var/folders/3z/fyvld5jd6lxbb7nt49h4jx1h0000gn/T/tmp1chq5qes']
[2022-01-05 18:23:44,903] {standard_task_runner.py:77} INFO - Job 9: Subtask also_run_this
[2022-01-05 18:23:44,950] {logging_mixin.py:109} INFO - Running <TaskInstance: example_bash_operator.also_run_this scheduled__2022-01-04T00:00:00+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2022-01-05 18:23:44,991] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=example_bash_operator
AIRFLOW_CTX_TASK_ID=also_run_this
AIRFLOW_CTX_EXECUTION_DATE=2022-01-04T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-04T00:00:00+00:00
[2022-01-05 18:23:44,993] {subprocess.py:62} INFO - Tmp dir root location: 
 /var/folders/3z/fyvld5jd6lxbb7nt49h4jx1h0000gn/T
[2022-01-05 18:23:44,994] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo "run_id=scheduled__2022-01-04T00:00:00+00:00 | dag_run=<DagRun example_bash_operator @ 2022-01-04 00:00:00+00:00: scheduled__2022-01-04T00:00:00+00:00, externally triggered: False>"']
[2022-01-05 18:23:45,001] {subprocess.py:85} INFO - Output:
[2022-01-05 18:23:45,004] {subprocess.py:89} INFO - run_id=scheduled__2022-01-04T00:00:00+00:00 | dag_run=<DagRun example_bash_operator @ 2022-01-04 00:00:00+00:00: scheduled__2022-01-04T00:00:00+00:00, externally triggered: False>
[2022-01-05 18:23:45,004] {subprocess.py:93} INFO - Command exited with return code 0
[2022-01-05 18:23:45,024] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=also_run_this, execution_date=20220104T000000, start_date=20220105T125344, end_date=20220105T125345
[2022-01-05 18:23:45,044] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-05 18:23:45,070] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
