[2022-01-06 15:23:49,398] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: new_description.print_date manual__2022-01-06T09:53:46.125674+00:00 [queued]>
[2022-01-06 15:23:49,407] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: new_description.print_date manual__2022-01-06T09:53:46.125674+00:00 [queued]>
[2022-01-06 15:23:49,407] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-06 15:23:49,407] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-01-06 15:23:49,407] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-06 15:23:49,418] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): print_date> on 2022-01-06 09:53:46.125674+00:00
[2022-01-06 15:23:49,420] {standard_task_runner.py:52} INFO - Started process 59342 to run task
[2022-01-06 15:23:49,428] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'new_description', 'print_date', 'manual__2022-01-06T09:53:46.125674+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/new_description_dag.py', '--cfg-path', '/var/folders/3z/fyvld5jd6lxbb7nt49h4jx1h0000gn/T/tmpbv_q0ojc', '--error-file', '/var/folders/3z/fyvld5jd6lxbb7nt49h4jx1h0000gn/T/tmp5i226f5f']
[2022-01-06 15:23:49,431] {standard_task_runner.py:77} INFO - Job 34: Subtask print_date
[2022-01-06 15:23:49,486] {logging_mixin.py:109} INFO - Running <TaskInstance: new_description.print_date manual__2022-01-06T09:53:46.125674+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2022-01-06 15:23:49,534] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=new_description
AIRFLOW_CTX_TASK_ID=print_date
AIRFLOW_CTX_EXECUTION_DATE=2022-01-06T09:53:46.125674+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-01-06T09:53:46.125674+00:00
[2022-01-06 15:23:49,536] {subprocess.py:62} INFO - Tmp dir root location: 
 /var/folders/3z/fyvld5jd6lxbb7nt49h4jx1h0000gn/T
[2022-01-06 15:23:49,537] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'date']
[2022-01-06 15:23:49,545] {subprocess.py:85} INFO - Output:
[2022-01-06 15:23:49,554] {subprocess.py:89} INFO - Thu Jan  6 15:23:49 IST 2022
[2022-01-06 15:23:49,555] {subprocess.py:93} INFO - Command exited with return code 0
[2022-01-06 15:23:49,576] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=new_description, task_id=print_date, execution_date=20220106T095346, start_date=20220106T095349, end_date=20220106T095349
[2022-01-06 15:23:49,612] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-06 15:23:49,643] {local_task_job.py:264} INFO - 2 downstream tasks scheduled from follow-on schedule check
